filegroup(
    name = "resources",
    srcs = glob([
        "*",
    ]),
    visibility = [
        "//bookmarker/server/src/main/java/me/a6n/bookmarker:__subpackages__",
        "//bookmarker/server/src/test/java/me/a6n/bookmarker:__subpackages__",
    ],
)
