load("@io_bazel_rules_scala//scala:scala.bzl", "scala_binary", "scala_library", "scala_test")

scala_binary(
    name = "scalaplayground",
    srcs = glob([
        "*.scala",
    ]),
    main_class = "me.a6n.scalaplayground.App",
)
